DjDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
]

main/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^artist/$',views.Artist_List,name='artist_list'),
    #url(r'album/$', views.IndexView.as_view(), name='album'),
    #url(r'^(?P<pk>[0-9]+)/$', views.AlbumDetail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^artist/(?P<pk>[0-9]+)/$',views.ArtistAlbum,name='artist_album'),
    url(r'^contact/$',views.Contact,name='contact'),
    url(r'^albums/$',views.Album_List,name='album_list'),
    url(r'^punk/$',views.punkView,name='punk'),
    url(r'^rock/$',views.rockView,name='rock'),
    url(r'^metal/$',views.metalView,name='metal'),
    url(r'^swing/$',views.swingView,name='swing'),
    url(r'^electro/$',views.electroView,name='electro'),
    url(r'^pop/$',views.popView,name='pop'),

    #SEARCH ALBUMS ALPHABETICAL
    url(r'^albums/A/$',views.ASearch,name='A_search'),
    url(r'^albums/B/$',views.BSearch,name='B_search'),
    url(r'^albums/C/$',views.CSearch,name='C_search'),
    url(r'^albums/D/$', views.DSearch, name='D_search'),
    url(r'^albums/E/$', views.ESearch, name='E_search'),
    url(r'^albums/F/$', views.FSearch, name='F_search'),
    url(r'^albums/G/$', views.GSearch, name='G_search'),
    url(r'^albums/H/$', views.HSearch, name='H_search'),
    url(r'^albums/I/$', views.ISearch, name='I_search'),
    url(r'^albums/K/$', views.JSearch, name='J_search'),
    url(r'^albums/K/$', views.KSearch, name='K_search'),
    url(r'^albums/L/$', views.LSearch, name='L_search'),
    url(r'^albums/M/$', views.MSearch, name='M_search'),
    url(r'^albums/N/$', views.NSearch, name='N_search'),
    url(r'^albums/O/$', views.OSearch, name='O_search'),
    url(r'^albums/P/$', views.PSearch, name='P_search'),
    url(r'^albums/Q/$', views.QSearch, name='Q_search'),
    url(r'^albums/R/$', views.RSearch, name='R_search'),
    url(r'^albums/S/$', views.SSearch, name='S_search'),
    url(r'^albums/T/$', views.TSearch, name='T_search'),
    url(r'^albums/U/$', views.USearch, name='U_search'),
    url(r'^albums/V/$', views.VSearch, name='V_search'),
    url(r'^albums/W/$', views.WSearch, name='W_search'),
    url(r'^albums/X/$', views.XSearch, name='X_search'),
    url(r'^albums/Y/$', views.YSearch, name='Y_search'),
    url(r'^albums/Z/$', views.ZSearch, name='Z_search'),

]


main/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django import forms


class Artist(models.Model):
    artist_name = models.CharField(max_length=4000)
    is_band = models.BooleanField()
    artist_photo = models.CharField(max_length=1000)
    profile = models.CharField(max_length=4000)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __str__(self):
        return self.artist_name


class Record_Company(models.Model):
    company_name = models.CharField(max_length=250)
    location = models.CharField(max_length=1000)
    contact = models.CharField(max_length=250)
    founding = models.DateField()
    profile = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __str__(self):
        return self.company_name


class Album(models.Model):
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=500)
    style = models.CharField(max_length=100)
    date_of_release = models.DateField()
    total_duration = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    profile = models.CharField(max_length=4000)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE,null=True)
    record_company = models.ForeignKey(Record_Company, on_delete=models.CASCADE,null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)


    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title


class Song(models.Model):
    song_title = models.CharField(max_length=250)
    date_of_release = models.DateField()
    total_duration = models.CharField(max_length=100)
    song_link = models.CharField(max_length=1000)
    album = models.ForeignKey(Album, on_delete=models.CASCADE,null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __str__(self):
        return self.song_title

class EmailForm(forms.Form):
  firstname = forms.CharField(max_length=255)
  lastname = forms.CharField(max_length=255)
  email = forms.EmailField()
  subject = forms.CharField(max_length=255)
  botcheck = forms.CharField(max_length=5)
  message = forms.CharField()

templates/djdjango/album_list.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
        <div class="row">

            <div class="col-sm-12">
             <div class="panel panel-default">
                {% for album in albums %}
                    <div class="col-sm-4 col-lg-2">

                        <div class="thumbnail">

                            <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                                <div class="caption">
                                        <h2>{{ album.album_title }}</h2>
                                        <h2>{{ album.artist }}</h2>
                                        <div class="text-right">
                                           <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                                        </div>

                                        </div>
                                    </div>
                                </div>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/djdjango/artist_album.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
        <div class="row">


                {% for artist in artist_album %}
                    <div class="col-md-4">

                        <div class="thumbnail">

                            <img src="{{ artist.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                                <div class="caption">
                                        <h2>{{ artist.album_title }}</h2>
                                        <h2>{{ artist.artist }}</h2>
                                        <div class="text-right">
                                           <a href="{% url 'detail' artist.pk %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                                        </div>

                                        </div>
                                    </div>
                                </div>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}

templates/djdjango/artist_list.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
        <div class="row">

            <div class="col-sm-12">

                {% for artist in artist_list %}
                    <div class="col-md-4">

                        <div class="thumbnail">

                            <img src="{{ artist.artist_photo }}" class="img-responsive" style="width:200px;height:200px;">
                                <div class="caption">
                                        <h2>{{ artist.artist_name }}</h2>
                                        <div class="text-right">
                                           <a href="{% url 'artist_album' artist.pk %}" class="btn btn-primary btn-sm" role="button">View Artist Albums</a>
                                        </div>

                                        </div>
                                    </div>
                                </div>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/djdjango/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'djdjango/style.css' %}">
    <meta charset="UTF-8">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

       <!-- Add the script to the HEAD of your document -->
    <SCRIPT LANGUAGE="JavaScript">
    <!-- Begin
    var scrl = " DjDjango|The online music Library! <3 ";
    function scrlsts() {
     scrl = scrl.substring(1, scrl.length) + scrl.substring(0, 1);
     document.title = scrl;
     setTimeout("scrlsts()", 300);
     }
    //  End -->
    </script>


<!-- Add the event loader to the body tag as below -->

<body onLoad="scrlsts()">

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><img src="https://s23.postimg.org/bk672hkkr/Beats_Music_Logo.png" alt="Image"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'album_list' %}">Albums</a></li>
        <li><a href="{% url 'artist_list' %}">Artist</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Genre
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'rock' %}">Rock</a></li>
                <li><a href="{% url 'metal' %}">Metal</a></li>
                <li><a href="{% url 'punk' %}">Punk</a></li>
                <li><a href="{% url 'swing' %}">Swing</a></li>
                <li><a href="{% url 'pop' %}">Pop</a></li>
                <li><a href="{% url 'electro' %}">Electro</a></li>
            </ul>
        </li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <form class="navbar-form navbar-left" method="get" action="/albums">
            <div class="form-group">
            <input type="text" name="q" class="form-control" placeholder="Search">
        </div>
            <button type="submit" class="btn btn-default">Submit</button>
      </form>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

<footer class="container-fluid text-center">
    <p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Άδεια Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"></a> <small>© Copyright <a href="mailto:nikol30992@hotmail.com" target="_top">Agisilaou Alexandra Nikoleta</a> | <a href="mailto:eyagstag@gmail.com" target="_top">Stagkos Vaggelis</a></small></p>
</footer>
</body>
</html>

templates/djdjango/contact.html
{% extends 'djdjango/base.html' %}
{% block content %}

    <div class="container-fluid songs-container">
        <div class="row">

                                                    <div class="col-sm-4 col-lg-2">
                                    <h2>Send e-mail to someone@example.com:</h2>

                                <form action="mailto:someone@example.com" method="post" enctype="text/plain">

                                    Name:<br>
                                <input type="text" name="name"><br>
                                E-mail:<br>
                                <input type="text" name="mail"><br>
                                Comment:<br>
                                <textarea rows="5" cols="50" name="message" placeholder="Leave your message here..."></textarea>
                                    </br>
                                <input type="submit" value="Send">
                                <input type="reset" value="Reset">
                                </form>
                                        </div>

                                        </div>
                                    </div>
                                </div>

            </div>

        </div>
    </div>

{% endblock %}

templates/djdjango/detail.html
{% extends 'djdjango/base.html' %}
{% block content %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="#">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                    <h2>{{ album.record_company }}</h2>
                </div>
            </div>


        </div>


         <div class="col-sm-8 col-md-9">

           <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Album Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>YouTube Link</th>
                            <th>Track Duration</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title}}</td>
                                <td>
                                    <a target="_blank" href="{{ song.song_link }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    {{ song.total_duration }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

         </div></div>


    <div class="container-fluid">
  <div class="row">
     <div class="col-md-4">

           <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Artist Info</h3>
                    {% for artist in album.artist_set.all %}
                    <p>{{ artist.profile }}</p>
                    {% endfor %}
                </div>
           </div>
           </div>
             <div class="col-md-8">

           <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Album Info</h3>
                    <p>{{ album.profile }}</p>
                </div>
           </div>
           </div>
  </div>
</div>

{% endblock %}

templates/djdjango/electro.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in electro %}
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h2>{{ album.artist }}</h2>
                        <div class="text-right">
                            <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}

templates/djdjango/homepage.html
{% extends 'djdjango/base.html' %}
{% block content %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://www.laptoprated.com/wp-content/uploads/2016/05/best-laptop-for-music-1200x400.png" alt="Image">
        <div class="carousel-caption">
          <h3> </h3>
          <p></p>
        </div>
      </div>

      <div class="item">
        <img src="http://www.mswritersandmusicians.com/wp-content/uploads/2014/10/jmurdock-blues.jpg" alt="Image">
        <div class="carousel-caption">
          <h3></h3>
          <p></p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<div class="container text-center">
  <h3>Latest Albums!</h3><br>
  <div class="row">
    <div class="col-md-8">
      <div class="container-fluid songs-container">
        <div class="row">
            {% for album in home|slice:":2" %}
                <div class="col-md-6">
                    <div class="thumbnail">
                        <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                            <div class="caption">
                                <h2>{{ album.album_title }}</h2>
                                <h2>{{ album.artist }}</h2>
                                <div class="text-right">
                                    <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                                </div>
                            </div>
                    </div>
                </div>
            {% endfor %}
        </div>
</div>
    </div>

    <div class="col-md-4">
      <div class="#">
        <div>
            <ul>
            <li>
                    <marquee onMouseOver="this.scrollAmount=0" onMouseOut="this.scrollAmount=2"bgcolor="#ffffff" scrollamount="1" direction="up" loop="true" width="95%" height="250">
                    <a href="http://straightonmusic.com/2017/01/oi-doors-epanakykloforoun-ton-prwto-toys-disko-gia-thn-50h-epeteio-toy/"><strong>Οι Doors επανακυκλοφορούν τον πρώτο τους δίσκο για την 50ή επέτειό του</strong></a>
                    </br>
            </li>
            </br>

            <li>
                    <a href="http://m.lifo.gr/articles/mikropragmata/117923"><strong>Το νέο βίντεοκλίπ του Moby είναι ένα καρτούν αριστούργημα που κανείς δεν πρέπει να το χάσει!</strong></a>
            </li>
            </br>

            <li>
                    <a href="http://www.musicity.gr/synaylies/item/7898-placebo-rockwave-festival-terravibe-2017"><strong>Rock Wave Festival 2017: Placebo και Silvert Hoyem για την 1η μέρα!</strong></a>
            </li>
            </br>

            <li>
                    <a href="http://straightonmusic.com/2016/10/ozzy-osbourne-ayto-einai-to-pio-tromaktiko-tragoydi-olwn-twn-epoxwn/"><strong>Ozzy Osbourne: «Αυτό είναι το πιο τρομακτικό τραγούδι όλων των εποχών»</strong></a>
            </li>
            </br>

            <li>
                    <a href="http://www.nme.com/news/music/various-artists-5318-1555213"><strong>Marilyn Manson and The Prodigy’s record label announces 30th anniversary gigs and box-set</strong></a>
            </li>
            </br>

            <li>
                    <a href="http://www.jumpingfish.gr/article/surprise-o-bob-dylan-kerdise-to-nompel-logotehnia/343766?utm_source=Facebook&utm_medium=JF-Page&utm_term=slot-3&utm_content=link&utm_campaign=quad-fb-traffic"><strong>Surprise! Ο Bob Dylan κέρδισε το Νόμπελ Λογοτεχνίας 2016. Oρίστε 10 από τους καλύτερους στίχους του.</strong></a>
            </li>
                    </marquee>
            </ul>

        </div>
      </div>

    </div>
  </div>
</div><br>
{% endblock %}

templates/djdjango/metal.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in metal %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h2>{{ album.artist }}</h2>
                        <div class="text-right">
                            <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

templates/djdjango/pop.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in pop %}
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h2>{{ album.artist }}</h2>
                        <div class="text-right">
                            <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
    </div>
</div>
</div>

{% endblock %}

templates/djdjango/punk.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in punk %}
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                    <div class="caption">
                        <h2>{{ album.album_title }}</h2>
                        <h2>{{ album.artist }}</h2>
                        <div class="text-right">
                            <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}

templates/djdjango/rock.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in rock %}
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h2>{{ album.artist }}</h2>
                    <div class="text-right">
                        <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
 </div>
</div>

{% endblock %}

templates/djdjango/search_bar.html

    <div class="container" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <div class="btn-toolbar">
    <div class="btn-group btn-group-sm">
      <button class="btn btn-default">A</button>
      <button class="btn btn-default">B</button>
      <button class="btn btn-default">C</button>
      <button class="btn btn-default">D</button>
      <button class="btn btn-default">E</button>
      <button class="btn btn-default">F</button>
      <button class="btn btn-default">G</button>
      <button class="btn btn-default">H</button>
      <a href="{% url 'I_search' %}" class="btn btn-default">I</a>
      <button class="btn btn-default">J</button>
      <button class="btn btn-default">K</button>
      <button class="btn btn-default">L</button>
      <button class="btn btn-default">M</button>
      <button class="btn btn-default">N</button>
      <button class="btn btn-default">O</button>
      <button class="btn btn-default">P</button>
      <button class="btn btn-default">Q</button>
      <button class="btn btn-default">R</button>
      <button class="btn btn-default">S</button>
      <button class="btn btn-default">T</button>
      <button class="btn btn-default">U</button>
      <button class="btn btn-default">V</button>
      <button class="btn btn-default">W</button>
      <button class="btn btn-default">X</button>
      <button class="btn btn-default">Y</button>
      <button class="btn btn-default">Z</button>
    </div>
  </div>
</div>

<br />
<br />

templates/djdjango/swing.html
{% extends 'djdjango/base.html' %}

{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        {% for album in swing %}
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="{{ album.album_logo }}" class="img-responsive" style="width:200px;height:200px;">
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h2>{{ album.artist }}</h2>
                    <div class="text-right">
                        <a href="{% url 'detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                    </div>
                 </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}